---
name: homelab-ring-mqtt-configuration
description: "Homelab: Configuration for Ring MQTT"
visibility: public
protected: true
topics:
  - mqtt
  - configuration
  - ring
  - homelab

rulesets:
  branch:
    enabled: true
    requiredChecks:
      - Dependency Review

accessPermissions:
  vault:
    enabled: false
