---
name: homelab-home-cluster-applications
description: "Homelab: Applications running on the Kubernetes home-cluster"
visibility: public
protected: true
topics:
  - kubernetes
  - homelab
  - gitops
  - fluxcd

rulesets:
  branch:
    enabled: false

accessPermissions:
  vault:
    enabled: false
