---
name: homelab-home-assistant-configuration
description: "Homelab: Configuration for Home Assistant"
visibility: public
protected: true
topics:
  - configuration
  - homelab
  - homeassistant
  - homeassistant-configuration

rulesets:
  branch:
    enabled: false

accessPermissions:
  doppler: false
  vault:
    enabled: false
