---
name: homelab-kubernetes-home-applications
description: "Homelab: Applications running on the Kubernetes home-cluster"
visibility: public
protected: true
topics:
  - kubernetes
  - homelab
  - gitops
  - argocd-applications

rulesets:
  branch:
    enabled: false

accessPermissions:
  doppler: false
