---
name: homelab-home-assistant-configuration
description: "Homelab: Configuration for Home Assistant"
visibility: public
protected: true
topics:
  - configuration
  - homelab
  - homeassistant
  - homeassistant-configuration

rulesets:
  branch:
    enabled: true
    requiredChecks:
      - Dependency Review
      - Lint YAML
      - Verify Home Assistant Configuration (stable)
      - Verify Home Assistant Configuration (beta)
      - Verify Home Assistant Configuration (dev)

accessPermissions:
  vault:
    enabled: false
