---
name: homelab-home-assistant-configuration
description: "Homelab: Configuration for Home Assistant"
visibility: public
protected: true
topics:
  - configuration
  - homelab
  - home-assistant
  - home-assistant-configuration

rulesets:
  branch:
    enabled: false

accessPermissions:
  doppler: false
