---
name: homelab-esphome-firmware
description: "Homelab: ESPHome firmware configurations"
visibility: public
protected: true
topics:
  - esphome
  - esphome-config
  - homelab

rulesets:
  branch:
    enabled: true
    requiredChecks:
      - Dependency Review
      - YAML Lint
      - Verify Builds

accessPermissions:
  vault:
    enabled: true
  google:
    region: europe-west4
    project: tuxnet-385112
    hmacKey: true
