---
name: homelab-ring-mqtt-configuration
description: "Homelab: Configuration for Ring MQTT"
visibility: public
protected: true
topics:
  - mqtt
  - configuration
  - ring
  - homelab

rulesets:
  branch:
    enabled: false

accessPermissions:
  doppler: false
